---
#
#(작업1) 다음 조건으로 RC를 사용하는 rc-lab.yml 파일을 생성하고 다음과 같은 동작시킨다.
#labels(name: apache, app: main, rel: stable)를 가지는 httpd:2.2 버전의 pod를 2개 운영한다.- RC 이름: rc-mainui- 이미지 이름: httpd:2.2
#현재 디렉토리에 rc-lab.yml 파일이 생성되어야 하고, 애플리케이션 동작은 파일을 이용하여 실행한다.
#(작업2) 동작되는 httpd:2.2 버전의 컨테이너를 3개로 확장하는 명령을 적고 실행한다.
#(작업3) 작업이 완료 되었으면 정리 작업을 진행한다.
apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-mainui
spec:
  replicas: 2
  selector:
    app: main
    name: apache
    rel: stable
  template:
    metadata:
      name: rc-pod
      labels:
        app: main
        name: apache
        rel: stable
    spec:
      containers:
        - name: httpd-container
          image: httpd:2.2

