---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongodb-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      name: mongo-express-pod
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express:1.0.2-18
        ports:
        - containerPort: 8081
        env:
        - name: "ME_CONFIG_MONGODB_URL"
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key: database_url
        - name: "ME_CONFIG_BASICAUTH_ENABLED"
          value: "true"
        - name: "ME_CONFIG_BASICAUTH_USERNAME"
          value: "admin"
        - name: "ME_CONFIG_BASICAUTH_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password

---
kind: Service
apiVersion: v1
metadata:
  name: mongo-express-service
spec:
  type: LoadBalancer
  # clusterIP: 10.100.10.10
  selector:
    app: mongo-express
  ports:
  - port: 8081
    targetPort: 8081
    # nodePort: 30000
