# secret 파일 생성 yml
# 아이디 : echo -n '아이디' | base64
# 비밀번호 : echo -n '비밀번호' | base64
---
kind: Secret
apiVersion: v1
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: cm9vdA==
  mongo-root-password: cGFzc3dvcmQ=
