---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-env-pod
spec:
  containers:
    - name: nginx-container
      image: nginx:1.14
      ports:
      - containerPort: 80
      env:
      - name: MYVAR
        value: "testvalue"
