# 블루 그린 배포 실습
# 블루(현재) 그린(업데이트)
# kubectl edit service/service이름 에서 버전 변경
---
kind: Service
apiVersion: v1
metadata:
  name: blue-green-svc
spec:
  # type: ClusterIP
  # clusterIP: 10.233.10.10
  selector:
    app: web
    version: blue
  ports:
  - port: 80
    targetPort: 8080
